### PR TITLE
CAMEL-18506: replaced Async HTTP client with Java's own HTTP client in camel-telegram

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
@davsclaus @oscerd I am not well versed on the OSGI magic, so, please let me know if I missed anything. :sweat_smile:

**Review by oscerd — APPROVED** [review]
It seems to be fine. Did you run the full features test in platform/Karaf/features?

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
I am testing and correcting features if need to

**Comment by davsclaus** [comment]
Okay I cannot remember how to tell karaf that this requires java 11 as it cannot import java.net.http in karaf 4.3.x

**Comment by grgrzybek** [comment]
Add:
```xml
<Require-Capability>osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"</Require-Capability>
```

to maven-bundle-configuration.

Or (more or less awkward - depends):
```xml
<_noee>false</_noee>
```

**Comment by grgrzybek** [comment]
For example in camel-core-osgi-3.18.2.jar I see:
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"
```

So you're fine already - this is taken from maven-compiler-plugin config.

**Comment by davsclaus** [comment]
Ah so we need to add this to camel-telegram and not the feature.xml file (darn want to keep osgi only in karaf)

**Comment by davsclaus** [comment]
btw karaf 4.4.1 exports the java.net.http package - 4.3.7 does not
https://issues.apache.org/jira/browse/CAMEL-18531

**Comment by grgrzybek** [comment]
4.4.1 is JDK11+ and someone decided that it's a good idea to "export" `java.*` packages - even if the specs (until R8) say that there's no need to do it.

**Comment by davsclaus** [comment]
Ok darn, upgrading to 4.4.x then have failures in 2 other features files. and 4.3.x do not work with java 11 out of the box. 
But we should upgrade to karaf 4.4.x as Camel is JDK11+ too.

**Pull request merged**
