### PR TITLE
Upgrade to Camel 4.7

### PR DESCRIPTION
**Pull request by essobedo**

### CODE REVIEW

**Comment by essobedo** [comment]
Waiting for Camel 4.7 to be released + Need to fix the integration test of camel-azure-storage-blob

**Comment by jbonofre** [comment]
It sounds good to me. I propose to wait Camel 4.7.0 before doing first camel-karaf release.

**Comment by essobedo** [comment]
> It sounds good to me. I propose to wait Camel 4.7.0 before doing first camel-karaf release.

yes, I agree, It is what I had in mind too :-)

**Comment by essobedo** [comment]
The integration test has been removed temporarily, it will be fixed by https://github.com/apache/camel-karaf/issues/428

**Pull request merged**
