### PR TITLE
CAMEL-18344: Supporting camel "camel-google-pubsub" and "camel-grpc" OSGi deployment

### PR DESCRIPTION
**Pull request by essobedo**
Fix for https://issues.apache.org/jira/browse/CAMEL-18344

## Motivation

The features camel-google-pubsub and camel-grpc have been removed from camel-karaf due to some integrations issues but as some users need it, it is important to put them back.

## Modifications:

* Re-add the features
* Use new servicemix-bundles that still need to be approved, merged, and released
* Fix camel-jira feature that is affected by the changes in the bundle google-http-client

### CODE REVIEW

**Comment by essobedo** [comment]
Waiting for:

* https://github.com/apache/servicemix-bundles/pull/179
* https://github.com/apache/servicemix-bundles/pull/180
* https://github.com/apache/servicemix-bundles/pull/181
* https://github.com/apache/servicemix-bundles/pull/182
* https://github.com/apache/camel/pull/8157

**Comment by jbonofre** [comment]
It would be great to rebase once I merge the refactoring PR. I'm fixing the tests right now.

**Comment by essobedo** [comment]
The only drawback I’ve met with the feature `camel-grpc` is the fact that we need javassist to be part of the dependencies of the bundle including the generated classes

**Comment by essobedo** [comment]
> It would be great to rebase once I merge the refactoring PR. I'm fixing the tests right now.

@jbonofre ok no problem, BTW I would need a fix for 3.18.x so it is still interesting to have those commits before the rebase

**Comment by essobedo** [comment]
> Ok. It makes sense. Then I will do the other way: review/merge/cherry pick and after rebasing refactoring on main.

Many thanks for proposing 🙏  however unless you can wait a bit before merging your PR, I'm afraid I would need to rebase it myself since this PR has many dependencies that could take some time before being reviewed, merged, and released. Once done, I still have the modify my PR, to get rid of all the snapshot dependencies

**Comment by essobedo** [comment]
Could someone review it before the release of today? 🙏

**Comment by jbonofre** [comment]
I'm on it

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@essobedo can you send the PR for the 3.18.x backport

**Comment by essobedo** [comment]
@davsclaus yes of course

**Comment by jbonofre** [comment]
Ok. I was about to review and merge. No worries.

**Comment by essobedo** [comment]
Backport PR https://github.com/apache/camel-karaf/pull/185

**Pull request merged**
