### PR TITLE
Update features.xml

### PR DESCRIPTION
**Pull request by ReLS972**
change range [6.2,6.2] to [6.2,6.3) make it work with karaf-assembly

### CODE REVIEW

**Comment by davsclaus** [comment]
What problem do you have, and what does karaf-assembly complain about?

**Comment by ReLS972** [comment]
it produce this :
`2022-01-22T20:25:54,730 | WARN  | FelixStartLevel  | AetherBasedResolver              | 2 - org.ops4j.pax.url.mvn - 2.6.10 | Error resolving artifact org.hibernate.validator:hibernate-validator-osgi-karaf-features:xml:features:[6.2,6.2]: [Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in local (C:\Users\---\.m2\repository), Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in apache (https://repository.apache.org/content/groups/snapshots-group/), Could not find metadata org.hibernate.validator:hiberna
java.io.IOException: Error resolving artifact org.hibernate.validator:hibernate-validator-osgi-karaf-features:xml:features:[6.2,6.2]: [Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in local (C:\Users\---\.m2\repository), Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in apache (https://repository.apache.org/content/groups/snapshots-group/), Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in ops4j.sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/ops4j-snapshots/)]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803) [!/:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:780) [!/:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657) [!/:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598) [!/:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565) [!/:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:555) [!/:?]
	at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123) [!/:?]
	at java.net.URL.openStream(URL.java:1140) [?:?]
	at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:114) [!/:?]
	at org.apache.karaf.features.internal.service.RepositoryImpl.<init>(RepositoryImpl.java:51) [!/:?]
	at org.apache.karaf.features.internal.service.RepositoryCacheImpl.create(RepositoryCacheImpl.java:51) [!/:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.getFeatureCache(FeaturesServiceImpl.java:611) [!/:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.ensureCacheLoaded(FeaturesServiceImpl.java:582) [!/:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.listRequiredRepositories(FeaturesServiceImpl.java:514) [!/:?]
	at org.apache.karaf.deployer.features.FeatureDeploymentListener.bundleChanged(FeatureDeploymentListener.java:247) [!/:?]
	at org.apache.karaf.deployer.features.FeatureDeploymentListener.init(FeatureDeploymentListener.java:90) [!/:?]
	at org.apache.karaf.deployer.features.osgi.Activator$DeploymentFinishedListener.deploymentEvent(Activator.java:86) [!/:?]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.registerListener(FeaturesServiceImpl.java:296) [!/:?]
	at org.apache.karaf.deployer.features.osgi.Activator.doStart(Activator.java:53) [!/:?]
	at org.apache.karaf.util.tracker.BaseActivator.start(BaseActivator.java:92) [!/:?]
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698) [org.apache.felix.framework-6.0.5.jar:?]
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402) [org.apache.felix.framework-6.0.5.jar:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308) [org.apache.felix.framework-6.0.5.jar:?]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539) [org.apache.felix.framework-6.0.5.jar:?]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [org.apache.felix.framework-6.0.5.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: shaded.org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in local (C:\Users\---\.m2\repository)
		at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolve(DefaultMetadataResolver.java:220) ~[!/:?]
		at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver.resolveMetadata(DefaultMetadataResolver.java:178) ~[!/:?]
		at shaded.org.apache.maven.repository.internal.DefaultVersionRangeResolver.getVersions(DefaultVersionRangeResolver.java:198) ~[!/:?]
		at shaded.org.apache.maven.repository.internal.DefaultVersionRangeResolver.resolveVersionRange(DefaultVersionRangeResolver.java:148) ~[!/:?]
		at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveVersionRange(DefaultRepositorySystem.java:232) ~[!/:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveLatestVersionRange(AetherBasedResolver.java:1060) [!/:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:765) [!/:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657) [!/:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598) [!/:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565) [!/:?]
		at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:555) [!/:?]
		at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123) [!/:?]
		at java.net.URL.openStream(URL.java:1140) [?:?]
		at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:114) [!/:?]
		at org.apache.karaf.features.internal.service.RepositoryImpl.<init>(RepositoryImpl.java:51) [!/:?]
		at org.apache.karaf.features.internal.service.RepositoryCacheImpl.create(RepositoryCacheImpl.java:51) [!/:?]
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.getFeatureCache(FeaturesServiceImpl.java:611) [!/:?]
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.ensureCacheLoaded(FeaturesServiceImpl.java:582) [!/:?]
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.listRequiredRepositories(FeaturesServiceImpl.java:514) [!/:?]
		at org.apache.karaf.deployer.features.FeatureDeploymentListener.bundleChanged(FeatureDeploymentListener.java:247) [!/:?]
		at org.apache.karaf.deployer.features.FeatureDeploymentListener.init(FeatureDeploymentListener.java:90) [!/:?]
		at org.apache.karaf.deployer.features.osgi.Activator$DeploymentFinishedListener.deploymentEvent(Activator.java:86) [!/:?]
		at org.apache.karaf.features.internal.service.FeaturesServiceImpl.registerListener(FeaturesServiceImpl.java:296) [!/:?]
		at org.apache.karaf.deployer.features.osgi.Activator.doStart(Activator.java:53) [!/:?]
		at org.apache.karaf.util.tracker.BaseActivator.start(BaseActivator.java:92) [!/:?]
		at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698) [org.apache.felix.framework-6.0.5.jar:?]
		at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402) [org.apache.felix.framework-6.0.5.jar:?]
		at org.apache.felix.framework.Felix.startBundle(Felix.java:2308) [org.apache.felix.framework-6.0.5.jar:?]
		at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539) [org.apache.felix.framework-6.0.5.jar:?]
		at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [org.apache.felix.framework-6.0.5.jar:?]
		at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: shaded.org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in apache (https://repository.apache.org/content/groups/snapshots-group/)
		at shaded.org.eclipse.aether.connector.basic.MetadataTransportListener.transferFailed(MetadataTransportListener.java:48) ~[?:?]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368) ~[?:?]
		at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75) ~[?:?]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642) ~[?:?]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:235) ~[?:?]
		at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:580) ~[?:?]
		at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
		at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: shaded.org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata org.hibernate.validator:hibernate-validator-osgi-karaf-features/maven-metadata.xml in ops4j.sonatype.snapshots.deploy (https://oss.sonatype.org/content/repositories/ops4j-snapshots/)
		at shaded.org.eclipse.aether.connector.basic.MetadataTransportListener.transferFailed(MetadataTransportListener.java:48) ~[?:?]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368) ~[?:?]
		at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75) ~[?:?]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642) ~[?:?]
		at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:235) ~[?:?]
		at shaded.org.eclipse.aether.internal.impl.DefaultMetadataResolver$ResolveTask.run(DefaultMetadataResolver.java:580) ~[?:?]
		at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
		at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: shaded.org.eclipse.aether.resolution.VersionRangeResolutionException: Error resolving artifact org.hibernate.validator:hibernate-validator-osgi-karaf-features:xml:features:[6.2,6.2]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveLatestVersionRange(AetherBasedResolver.java:1068) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:765) ~[?:?]
	... 24 more`

**Comment by ReLS972** [comment]
when i try to build a custom distribution using org.apache.karaf.tooling:karaf-maven-plugin, it's fail because maven unable to get the rigth version of the repository.

**Comment by oscerd** [comment]
On main i removed the feature repository directly

**Comment by davsclaus** [comment]
Okay so on 3.14.x then this PR seems okay in case it makes maven happy to download 6.2.x.
However we should likely avoid this feature ranges in the first place and use known versions with what we test and release together.

**Comment by davsclaus** [comment]
@oscerd do we need this for 3.15 onwards, if its removed and not really in use then I think this is okay.
But for 3.14.x we have a 3.14.0 release where this feature is already there
https://github.com/apache/camel-karaf/blob/camel-karaf-3.14.0/platforms/karaf/features/src/main/resources/features.xml#L23

**Comment by davsclaus** [comment]
Merging so gregor can cut the release tomorrow

**Comment by oscerd** [comment]
For 3.15.0 i just removed the repo and used the exact same set of bundles in the two related components. This PR is good, but I think we should avoid external features repository where it is possible. For 3.14.x, as LTS we need to maintain the feature repo from hibernate validator

**Pull request merged**
