### PR TITLE
Ref #539: Upgrade to Camel 4.8.1

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by essobedo** [comment]
Warning it looks like you are trying to upgrade to camel 4.9, did you check out the tag 4.8.1 before launching the upgrade tool?

**Comment by essobedo** [comment]
Check the root pom file, it should look like https://github.com/apache/camel-karaf/pull/541/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8

I guess I need to improve the readme of the upgrade tool to indicate that the target tag needs to be checked out first before launching the upgrade tool

**Comment by jbonofre** [comment]
Yes, I checkout on the camel 4.8.1 tag but I had another process (build) that checkout to `main` while doing the update.

**Comment by jbonofre** [comment]
It should be OK now.

**Pull request merged**
