### PR TITLE
Adding Jenkins file for PPC64LE JDK11

### PR DESCRIPTION
**Pull request by sanskruti1098**
Hi @oscerd to enable JDK11 jobs for power for camel-karaf-3.21.x request to review and merge it.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I don't know when I'll have the time to create the jobs for this.

**Comment by sanskruti1098** [comment]
Hi @oscerd can you please share job link for this?

**Comment by oscerd** [comment]
I didn't create the job.

**Comment by oscerd** [comment]
https://ci-builds.apache.org/job/Camel/job/Camel%20Karaf%20Build%203.21.x%20(ppc64le)/job/camel-3.21.x/1/console

**Comment by sanskruti1098** [comment]
Thank you!

**Pull request merged**
