### PR TITLE
[CAMEL-15226] Refactore camel-karaf to use simpler structure

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
This looks good to me, I'd like to have a revision by @davsclaus too.

**Review by davsclaus — APPROVED** [review]

**Comment by jbonofre** [comment]
@oscerd @davsclaus thanks for your feedback guys. I'm doing a full pass on tests, etc before merging.

**Comment by oscerd** [comment]
Needs to be rebased.

**Review by davsclaus — CHANGES_REQUESTED** [review]
We leave camel-karaf 3.x as-is, and can do a restructure when the project is moved to Apache Karaf

**Comment by jbonofre** [comment]
@davsclaus fair enought, I will rework this one.

**Comment by davsclaus** [comment]
closing old PR.

**Pull request closed without merging**
