### PR TITLE
CAMEL-2983 - resteasy component

### PR DESCRIPTION
**Pull request by onderson**
my knowledge on this is a bit limited. Not sure why it may be failing. any help appreciated. @jbonofre @oscerd

### CODE REVIEW

**Comment by onderson** [comment]
@oscerd do you have a hint you can share with me for below;

> ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.2.8:verify (validate) on project apache-camel: Verification failures: Verification failures:
[ERROR] 	Feature resolution failed for [camel-resteasy/3.3.0.SNAPSHOT]
[ERROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-resteasy; type=karaf.feature; version=3.3.0.SNAPSHOT; filter:="(&(osgi.identity=camel-resteasy)(type=karaf.feature)(version>=3.3.0.SNAPSHOT))" [caused by: Unable to resolve camel-resteasy/3.3.0.SNAPSHOT: missing requirement [camel-resteasy/3.3.0.SNAPSHOT] osgi.identity; osgi.identity=xml-specs-api; type=karaf.feature; version="[3.3.0.SNAPSHOT,3.3.0.SNAPSHOT]"]

Thanks

**Comment by oscerd** [comment]
This needs to be deployed on the snapshot repository of ASF, I suggest you, to run Karaf container first and add the your generated features file there. Btw it's not your fault, we need to add the component in main camel repo first

**Comment by onderson** [comment]
i'll rebase fairly soon.

**Comment by onderson** [comment]
rebased but seem to have the same issue. any help appreciated.

**Comment by oscerd** [comment]
Resteasy is not OSGi friendly, also wrapping all the JARs is not really OSGIsh, so I'd say we won't support camel-resteasy in camel-karaf.

**Comment by onderson** [comment]
ok then. no issues. cheers.

**Pull request closed without merging**
